# Generated by Django 3.2.5 on 2022-07-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_mfa_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(default='DEFAULT VALUE', help_text='Enter the answer to the above security question.', max_length=50, verbose_name='Security Answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(default='DEFAULT VALUE', help_text='Enter a security question that only you will know the answer to.', max_length=255, verbose_name='Security Question'),
        ),
    ]
