# Generated by Django 4.0.6 on 2022-07-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='others_notified',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='person_id',
            field=models.IntegerField(),
        ),
    ]
