# Generated by Django 4.0.6 on 2022-07-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_report_others_notified_alter_report_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='person_id',
            field=models.CharField(max_length=10),
        ),
    ]
