# Generated by Django 4.0.6 on 2022-07-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_report_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='data_breach_details',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='report',
            name='responsible_party',
            field=models.TextField(max_length=1000),
        ),
    ]
